version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dokani-laravel-app
    ports:
      - "9000:9000" # Map host port 9000 to container port 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dokani@root123
      MYSQL_DATABASE: dokani_app
      MYSQL_USER: dokani
      MYSQL_PASSWORD: dokani@123
    ports:
      - "3306:3306" # Map host port 3306 to MySQL port 3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: dokani@root123
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80" # Map host port 8080 to phpMyAdmin port 80
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"   # Map host port 8000 to Nginx port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
